=== DanielArndt/netmate-flowcalc/etc/filterval.dtd
<?xml version ="1.0" encoding="UTF-8"?>
<!-- The Document Type Definition (DTD) for the file -->

<!ELEMENT FILTERVAL (DEF)*>
<!ELEMENT DEF (#PCDATA)>
<!ATTLIST DEF
NAME CDATA #REQUIRED
TYPE (UInt8|SInt8|UInt16|SInt16|UInt32|SInt32|UInt64|SInt64|Bool|Binary|String|IPAddr|IP6Addr) "String"
>

=== DanielArndt/netmate-flowcalc/etc/filterval.xml
<?xml version ="1.0" encoding="UTF-8"?>
<!DOCTYPE FILTERVAL SYSTEM "filterval.dtd">
<FILTERVAL>

  <!-- my constants -->
  <DEF NAME="myhost" TYPE="IPAddr">193.175.133.179</DEF>

  <!-- constants from /etc/protocols -->
  <DEF NAME="ip" TYPE="UInt8">0</DEF>
  <DEF NAME="hopopt" TYPE="UInt8">0</DEF>
  <DEF NAME="icmp" TYPE="UInt8">1</DEF>
  <DEF NAME="igmp" TYPE="UInt8">2</DEF>
  <DEF NAME="ggp" TYPE="UInt8">3</DEF>
  <DEF NAME="st" TYPE="UInt8">5</DEF>
  <DEF NAME="tcp" TYPE="UInt8">6</DEF>
  <DEF NAME="cbt" TYPE="UInt8">7</DEF>
  <DEF NAME="egp" TYPE="UInt8">8</DEF>
  <DEF NAME="igp" TYPE="UInt8">9</DEF>
  <DEF NAME="bbn-rcc-mon" TYPE="UInt8">10</DEF>
  <DEF NAME="nvp-ii" TYPE="UInt8">11</DEF>
  <DEF NAME="pup" TYPE="UInt8">12</DEF>
  <DEF NAME="argus" TYPE="UInt8">13</DEF>
  <DEF NAME="emcon" TYPE="UInt8">14</DEF>
  <DEF NAME="xnet" TYPE="UInt8">15</DEF>
  <DEF NAME="chaos" TYPE="UInt8">16</DEF>
  <DEF NAME="udp" TYPE="UInt8">17</DEF>
  <DEF NAME="mux" TYPE="UInt8">18</DEF>
  <DEF NAME="dcn-meas" TYPE="UInt8">19</DEF>
  <DEF NAME="hmp" TYPE="UInt8">20</DEF>
  <DEF NAME="prm" TYPE="UInt8">21</DEF>
  <DEF NAME="xns-idp" TYPE="UInt8">22</DEF>
  <DEF NAME="trunk-1" TYPE="UInt8">23</DEF>
  <DEF NAME="trunk-2" TYPE="UInt8">24</DEF>
  <DEF NAME="leaf-1" TYPE="UInt8">25</DEF>
  <DEF NAME="leaf-2" TYPE="UInt8">26</DEF>
  <DEF NAME="rdp" TYPE="UInt8">27</DEF>
  <DEF NAME="irtp" TYPE="UInt8">28</DEF>
  <DEF NAME="iso-tp4" TYPE="UInt8">29</DEF>
  <DEF NAME="netblt" TYPE="UInt8">30</DEF>
  <DEF NAME="mfe-nsp" TYPE="UInt8">31</DEF>
  <DEF NAME="merit-np" TYPE="UInt8">32</DEF>
  <DEF NAME="sep" TYPE="UInt8">33</DEF>
  <DEF NAME="3pc" TYPE="UInt8">34</DEF>
  <DEF NAME="idpr" TYPE="UInt8">35</DEF>
  <DEF NAME="xtp" TYPE="UInt8">36</DEF>
  <DEF NAME="ddp" TYPE="UInt8">37</DEF>
  <DEF NAME="idpr-cmtp" TYPE="UInt8">38</DEF>
  <DEF NAME="il" TYPE="UInt8">40</DEF>
  <DEF NAME="ipv6" TYPE="UInt8">41</DEF>
  <DEF NAME="sdrp" TYPE="UInt8">42</DEF>
  <DEF NAME="ipv6-route" TYPE="UInt8">43</DEF>
  <DEF NAME="ipv6-frag" TYPE="UInt8">44</DEF>
  <DEF NAME="idrp" TYPE="UInt8">45</DEF>
  <DEF NAME="rsvp" TYPE="UInt8">46</DEF>
  <DEF NAME="gre" TYPE="UInt8">47</DEF>
  <DEF NAME="mhrp" TYPE="UInt8">48</DEF>
  <DEF NAME="bna" TYPE="UInt8">49</DEF>
  <DEF NAME="esp" TYPE="UInt8">50</DEF>
  <DEF NAME="ah" TYPE="UInt8">51</DEF>
  <DEF NAME="i-nlsp" TYPE="UInt8">52</DEF>
  <DEF NAME="swipe" TYPE="UInt8">53</DEF>
  <DEF NAME="narp" TYPE="UInt8">54</DEF>
  <DEF NAME="mobile" TYPE="UInt8">55</DEF>
  <DEF NAME="tlsp" TYPE="UInt8">56</DEF>
  <DEF NAME="skip" TYPE="UInt8">57</DEF>
  <DEF NAME="ipv6-icmp" TYPE="UInt8">58</DEF>
  <DEF NAME="ipv6-nonxt" TYPE="UInt8">59</DEF>
  <DEF NAME="ipv6-opts" TYPE="UInt8">60</DEF>
  <DEF NAME="cftp" TYPE="UInt8">62</DEF>
  <DEF NAME="sat-expak" TYPE="UInt8">64</DEF>
  <DEF NAME="kryptolan" TYPE="UInt8">65</DEF>
  <DEF NAME="rvd" TYPE="UInt8">66</DEF>
  <DEF NAME="ippc" TYPE="UInt8">67</DEF>
  <DEF NAME="sat-mon" TYPE="UInt8">69</DEF>
  <DEF NAME="visa" TYPE="UInt8">70</DEF>
  <DEF NAME="ipcv" TYPE="UInt8">71</DEF>
  <DEF NAME="cpnx" TYPE="UInt8">72</DEF>
  <DEF NAME="cphb" TYPE="UInt8">73</DEF>
  <DEF NAME="wsn" TYPE="UInt8">74</DEF>
  <DEF NAME="pvp" TYPE="UInt8">75</DEF>
  <DEF NAME="br-sat-mon" TYPE="UInt8">76</DEF>
  <DEF NAME="sun-nd" TYPE="UInt8">77</DEF>
  <DEF NAME="wb-mon" TYPE="UInt8">78</DEF>
  <DEF NAME="wb-expak" TYPE="UInt8">79</DEF>
  <DEF NAME="iso-ip" TYPE="UInt8">80</DEF>
  <DEF NAME="vmtp" TYPE="UInt8">81</DEF>
  <DEF NAME="secure-vmtp" TYPE="UInt8">82</DEF>
  <DEF NAME="vines" TYPE="UInt8">83</DEF>
  <DEF NAME="ttp" TYPE="UInt8">84</DEF>
  <DEF NAME="nsfnet-igp" TYPE="UInt8">85</DEF>
  <DEF NAME="dgp" TYPE="UInt8">86</DEF>
  <DEF NAME="tcf" TYPE="UInt8">87</DEF>
  <DEF NAME="eigrp" TYPE="UInt8">88</DEF>
  <DEF NAME="ospfigp" TYPE="UInt8">89</DEF>
  <DEF NAME="sprite-rpc" TYPE="UInt8">90</DEF>
  <DEF NAME="larp" TYPE="UInt8">91</DEF>
  <DEF NAME="mtp" TYPE="UInt8">92</DEF>
  <DEF NAME="ax.25" TYPE="UInt8">93</DEF>
  <DEF NAME="ipip" TYPE="UInt8">94</DEF>
  <DEF NAME="micp" TYPE="UInt8">95</DEF>
  <DEF NAME="scc-sp" TYPE="UInt8">96</DEF>
  <DEF NAME="etherip" TYPE="UInt8">97</DEF>
  <DEF NAME="encap" TYPE="UInt8">98</DEF>
  <DEF NAME="any" TYPE="UInt8">99</DEF>
  <DEF NAME="gmtp" TYPE="UInt8">100</DEF>
  <DEF NAME="ifmp" TYPE="UInt8">101</DEF>
  <DEF NAME="pnni" TYPE="UInt8">102</DEF>
  <DEF NAME="pim" TYPE="UInt8">103</DEF>
  <DEF NAME="aris" TYPE="UInt8">104</DEF>
  <DEF NAME="scps" TYPE="UInt8">105</DEF>
  <DEF NAME="qnx" TYPE="UInt8">106</DEF>
  <DEF NAME="a/n" TYPE="UInt8">107</DEF>
  <DEF NAME="ipcomp" TYPE="UInt8">108</DEF>
  <DEF NAME="snp" TYPE="UInt8">109</DEF>
  <DEF NAME="compaq-peer" TYPE="UInt8">110</DEF>
  <DEF NAME="ipx-in-ip" TYPE="UInt8">111</DEF>
  <DEF NAME="vrrp" TYPE="UInt8">112</DEF>
  <DEF NAME="pgm" TYPE="UInt8">113</DEF>
  <DEF NAME="l2tp" TYPE="UInt8">115</DEF>
  <DEF NAME="ddx" TYPE="UInt8">116</DEF>
  <DEF NAME="iatp" TYPE="UInt8">117</DEF>
  <DEF NAME="stp" TYPE="UInt8">118</DEF>
  <DEF NAME="srp" TYPE="UInt8">119</DEF>
  <DEF NAME="uti" TYPE="UInt8">120</DEF>
  <DEF NAME="smp" TYPE="UInt8">121</DEF>
  <DEF NAME="sm" TYPE="UInt8">122</DEF>
  <DEF NAME="ptp" TYPE="UInt8">123</DEF>
  <DEF NAME="fire" TYPE="UInt8">125</DEF>
  <DEF NAME="crtp" TYPE="UInt8">126</DEF>
  <DEF NAME="crudp" TYPE="UInt8">127</DEF>
  <DEF NAME="sscopmce" TYPE="UInt8">128</DEF>
  <DEF NAME="iplt" TYPE="UInt8">129</DEF>
  <DEF NAME="sps" TYPE="UInt8">130</DEF>
  <DEF NAME="pipe" TYPE="UInt8">131</DEF>
  <DEF NAME="sctp" TYPE="UInt8">132</DEF>
  <DEF NAME="fc" TYPE="UInt8">133</DEF>
  <DEF NAME="rsvp-e2e-ignore" TYPE="UInt8">134</DEF>
  <DEF NAME="raw" TYPE="UInt8">255</DEF>

  <!-- constants from /etc/services -->
  <DEF NAME="tcpmux" TYPE="UInt16">1</DEF>
  <DEF NAME="compressnet" TYPE="UInt16">2</DEF>
  <DEF NAME="compressnet" TYPE="UInt16">3</DEF>
  <DEF NAME="rje" TYPE="UInt16">5</DEF>
  <DEF NAME="echo" TYPE="UInt16">7</DEF>
  <DEF NAME="discard" TYPE="UInt16">9</DEF>
  <DEF NAME="systat" TYPE="UInt16">11</DEF>
  <DEF NAME="daytime" TYPE="UInt16">13</DEF>
  <DEF NAME="qotd" TYPE="UInt16">17</DEF>
  <DEF NAME="msp" TYPE="UInt16">18</DEF>
  <DEF NAME="chargen" TYPE="UInt16">19</DEF>
  <DEF NAME="ftp-data" TYPE="UInt16">20</DEF>
  <DEF NAME="fsp" TYPE="UInt16">21</DEF>
  <DEF NAME="ssh" TYPE="UInt16">22</DEF>
  <DEF NAME="telnet" TYPE="UInt16">23</DEF>
  <DEF NAME="smtp" TYPE="UInt16">25</DEF>
  <DEF NAME="nsw-fe" TYPE="UInt16">27</DEF>
  <DEF NAME="msg-icp" TYPE="UInt16">29</DEF>
  <DEF NAME="msg-auth" TYPE="UInt16">31</DEF>
  <DEF NAME="dsp" TYPE="UInt16">33</DEF>
  <DEF NAME="time" TYPE="UInt16">37</DEF>
  <DEF NAME="rap" TYPE="UInt16">38</DEF>
  <DEF NAME="rlp" TYPE="UInt16">39</DEF>
  <DEF NAME="graphics" TYPE="UInt16">41</DEF>
  <DEF NAME="name" TYPE="UInt16">42</DEF>
  <DEF NAME="nameserver" TYPE="UInt16">42</DEF>
  <DEF NAME="nicname" TYPE="UInt16">43</DEF>
  <DEF NAME="mpm-flags" TYPE="UInt16">44</DEF>
  <DEF NAME="mpm" TYPE="UInt16">45</DEF>
  <DEF NAME="mpm-snd" TYPE="UInt16">46</DEF>
  <DEF NAME="ni-ftp" TYPE="UInt16">47</DEF>
  <DEF NAME="auditd" TYPE="UInt16">48</DEF>
  <DEF NAME="tacacs" TYPE="UInt16">49</DEF>
  <DEF NAME="re-mail-ck" TYPE="UInt16">50</DEF>
  <DEF NAME="la-maint" TYPE="UInt16">51</DEF>
  <DEF NAME="xns-time" TYPE="UInt16">52</DEF>
  <DEF NAME="domain" TYPE="UInt16">53</DEF>
  <DEF NAME="xns-ch" TYPE="UInt16">54</DEF>
  <DEF NAME="isi-gl" TYPE="UInt16">55</DEF>
  <DEF NAME="xns-auth" TYPE="UInt16">56</DEF>
  <DEF NAME="xns-mail" TYPE="UInt16">58</DEF>
  <DEF NAME="ni-mail" TYPE="UInt16">61</DEF>
  <DEF NAME="acas" TYPE="UInt16">62</DEF>
  <DEF NAME="covia" TYPE="UInt16">64</DEF>
  <DEF NAME="tacacs-ds" TYPE="UInt16">65</DEF>
  <DEF NAME="bootps" TYPE="UInt16">67</DEF>
  <DEF NAME="bootpc" TYPE="UInt16">68</DEF>
  <DEF NAME="tftp" TYPE="UInt16">69</DEF>
  <DEF NAME="gopher" TYPE="UInt16">70</DEF>
  <DEF NAME="netrjs-1" TYPE="UInt16">71</DEF>
  <DEF NAME="netrjs-2" TYPE="UInt16">72</DEF>
  <DEF NAME="netrjs-3" TYPE="UInt16">73</DEF>
  <DEF NAME="netrjs-4" TYPE="UInt16">74</DEF>
  <DEF NAME="deos" TYPE="UInt16">76</DEF>
  <DEF NAME="vettcp" TYPE="UInt16">78</DEF>
  <DEF NAME="finger" TYPE="UInt16">79</DEF>
  <DEF NAME="http" TYPE="UInt16">80</DEF>
  <DEF NAME="www" TYPE="UInt16">80</DEF>
  <DEF NAME="www-http" TYPE="UInt16">80</DEF>
  <DEF NAME="hosts2-ns" TYPE="UInt16">81</DEF>
  <DEF NAME="xfer" TYPE="UInt16">82</DEF>
  <DEF NAME="mit-ml-dev" TYPE="UInt16">83</DEF>
  <DEF NAME="ctf" TYPE="UInt16">84</DEF>
  <DEF NAME="mit-ml-dev" TYPE="UInt16">85</DEF>
  <DEF NAME="mfcobol" TYPE="UInt16">86</DEF>
  <DEF NAME="kerberos" TYPE="UInt16">88</DEF>
  <DEF NAME="su-mit-tg" TYPE="UInt16">89</DEF>
  <DEF NAME="dnsix" TYPE="UInt16">90</DEF>
  <DEF NAME="mit-dov" TYPE="UInt16">91</DEF>
  <DEF NAME="npp" TYPE="UInt16">92</DEF>
  <DEF NAME="dcp" TYPE="UInt16">93</DEF>
  <DEF NAME="objcall" TYPE="UInt16">94</DEF>
  <DEF NAME="supdup" TYPE="UInt16">95</DEF>
  <DEF NAME="dixie" TYPE="UInt16">96</DEF>
  <DEF NAME="swift-rvf" TYPE="UInt16">97</DEF>
  <DEF NAME="tacnews" TYPE="UInt16">98</DEF>
  <DEF NAME="metagram" TYPE="UInt16">99</DEF>
  <DEF NAME="hostname" TYPE="UInt16">101</DEF>
  <DEF NAME="iso-tsap" TYPE="UInt16">102</DEF>
  <DEF NAME="gppitnp" TYPE="UInt16">103</DEF>
  <DEF NAME="acr-nema" TYPE="UInt16">104</DEF>
  <DEF NAME="cso" TYPE="UInt16">105</DEF>
  <DEF NAME="csnet-ns" TYPE="UInt16">105</DEF>
  <DEF NAME="3com-tsmux" TYPE="UInt16">106</DEF>
  <DEF NAME="rtelnet" TYPE="UInt16">107</DEF>
  <DEF NAME="snagas" TYPE="UInt16">108</DEF>
  <DEF NAME="pop2" TYPE="UInt16">109</DEF>
  <DEF NAME="pop3" TYPE="UInt16">110</DEF>
  <DEF NAME="sunrpc" TYPE="UInt16">111</DEF>
  <DEF NAME="mcidas" TYPE="UInt16">112</DEF>
  <DEF NAME="auth" TYPE="UInt16">113</DEF>
  <DEF NAME="audionews" TYPE="UInt16">114</DEF>
  <DEF NAME="sftp" TYPE="UInt16">115</DEF>
  <DEF NAME="ansanotify" TYPE="UInt16">116</DEF>
  <DEF NAME="uucp-path" TYPE="UInt16">117</DEF>
