=== DanielArndt/netmate-flowcalc/etc/filterdef.dtd
<?xml version ="1.0" encoding="UTF-8"?>
<!-- The Document Type Definition (DTD) for the file -->

<!ELEMENT FILTERDEF (DEF | COND)*>
<!ELEMENT DEF (#PCDATA)>
<!ATTLIST DEF
REFER (MAC | IP | TRANS | DATA) #REQUIRED
OFFSET CDATA #REQUIRED
MASK CDATA "0xFF"
LENGTH CDATA "1" 
TYPE (UInt8|SInt8|UInt16|SInt16|UInt32|SInt32|UInt64|SInt64|Bool|Binary|String|IPAddr|IP6Addr) #REQUIRED 
REV CDATA ""
>
<!ELEMENT COND (DEF*)>
<!ATTLIST COND
        NAME CDATA #REQUIRED
        MASK CDATA "0xFF"
        VAL CDATA #REQUIRED
>

=== DanielArndt/netmate-flowcalc/etc/filterdef.xml
<?xml version ="1.0" encoding="UTF-8"?>
<!DOCTYPE FILTERDEF SYSTEM "filterdef.dtd">
<FILTERDEF>
  <!-- Ethernet -->
  <DEF REFER="MAC" OFFSET="0" LENGTH="6" TYPE="Binary" REV="SrcMAC">DstMAC</DEF>
  <DEF REFER="MAC" OFFSET="6" LENGTH="6" TYPE="Binary" REV="DstMAC">SrcMAC</DEF>

  <!-- IP -->
  <DEF REFER="IP" OFFSET="0" MASK="0xF0" TYPE="UInt8">IPVer</DEF>
  <DEF REFER="IP" OFFSET="1" TYPE="UInt8">IPToS</DEF>
  <DEF REFER="IP" OFFSET="8" TYPE="UInt8">IPTTL</DEF>
  <DEF REFER="IP" OFFSET="9" TYPE="UInt8">Proto</DEF>
  <DEF REFER="IP" OFFSET="12" TYPE="IPAddr" REV="DstIP">SrcIP</DEF>
  <DEF REFER="IP" OFFSET="16" TYPE="IPAddr" REV="SrcIP">DstIP</DEF>

  <DEF REFER="IP" OFFSET="1" TYPE="UInt8">TrafficClass</DEF>
  <DEF REFER="IP" OFFSET="2" TYPE="UInt16">FlowLabel</DEF>
  <DEF REFER="IP" OFFSET="6" TYPE="UInt8">Proto6</DEF>
  <DEF REFER="IP" OFFSET="7" TYPE="UInt8">HopLimit</DEF>
  <DEF REFER="IP" OFFSET="8" TYPE="IP6Addr" REV="DstIP6">SrcIP6</DEF>
  <DEF REFER="IP" OFFSET="24" TYPE="IP6Addr" REV="SrcIP6">DstIP6</DEF>

  <!-- ICMP -->
  <DEF REFER="TRANS" OFFSET="0" TYPE="UInt8">ICMPType</DEF> 
  <DEF REFER="TRANS" OFFSET="1" TYPE="UInt8">ICMPCode</DEF> 

  <!-- UDP, TCP -->
  <DEF REFER="TRANS" OFFSET="0" TYPE="UInt16" REV="DstPort">SrcPort</DEF>
  <DEF REFER="TRANS" OFFSET="2" TYPE="UInt16" REV="SrcPort">DstPort</DEF>
  <DEF REFER="TRANS" OFFSET="13" MASK="0x3F" TYPE="UInt8">TCPFlags</DEF>

</FILTERDEF>
