=== DanielArndt/netmate-flowcalc/etc/rulefile.dtd
<?xml version ="1.0" encoding="UTF-8"?>
<!-- The Document Type Definition (DTD) for the file -->

<!ELEMENT RULESET (GLOBAL, RULE*)>
<!ELEMENT GLOBAL (PREF|ACTION|EXPORT)*>
<!-- global configuration is overruled by per rule configuration -->
<!ELEMENT RULE (PREF|FILTER|ACTION|EXPORT)*>
<!ATTLIST RULESET
          ID CDATA #REQUIRED>
<!ATTLIST RULE
        ID CDATA #REQUIRED>
<!ELEMENT PREF (#PCDATA)>
<!ATTLIST PREF
        NAME CDATA #REQUIRED
        TYPE (UInt8|SInt8|UInt16|SInt16|UInt32|SInt32|UInt64|SInt64|Bool|Binary|String|IPAddr|IP6Addr) "String">
<!ELEMENT FILTER (#PCDATA)>
<!ATTLIST FILTER
        NAME CDATA #REQUIRED
        MASK CDATA "0xFF"
>
<!ELEMENT ACTION (PREF*)>
<!ATTLIST ACTION
        NAME CDATA #REQUIRED>
<!ELEMENT EXPORT (PREF*)>
<!ATTLIST EXPORT
        NAME CDATA #REQUIRED
>

=== DanielArndt/netmate-flowcalc/etc/example_rules1.xml
<?xml version ="1.0" encoding="UTF-8"?>
<!DOCTYPE RULESET SYSTEM "rulefile.dtd"> 
<RULESET ID="1">
  <!-- global part is the default for all rules -->
  <!-- overwritten by rule specific configuration -->
  <GLOBAL>
    <!-- how long the rules are active -->
    <PREF NAME="Duration">1000</PREF>

    <!-- export time interval -->
    <PREF NAME="Interval">1</PREF>
  </GLOBAL>
  <RULE ID="1">
    <!-- match all packets -->
    <FILTER NAME="SrcIP">*</FILTER>

    <ACTION NAME="capture">
    </ACTION>
 
    <!-- export tcpdump file, can be read with
         tcpdump -r -->
    <EXPORT NAME="bin_file">
      <PREF NAME="Filename">capture</PREF>
    </EXPORT>
  </RULE>
</RULESET>

=== DanielArndt/netmate-flowcalc/etc/example_rules3.xml
<?xml version ="1.0" encoding="UTF-8"?>
<!DOCTYPE RULESET SYSTEM "rulefile.dtd"> 
<RULESET ID="1">
  <GLOBAL>
    <PREF NAME="Duration">1000</PREF>
    <PREF NAME="Interval">2</PREF>
    <ACTION NAME="count"></ACTION>
    <ACTION NAME="show_ascii"></ACTION>
    <EXPORT NAME="text_file">
      <PREF NAME="Filename">ruleset1-export</PREF>
    </EXPORT>
    <EXPORT NAME="testexp">
    </EXPORT>
  </GLOBAL>
  <RULE ID="1">
    <FILTER NAME="SrcIP">*</FILTER>

    <ACTION NAME="testmod">
      <PREF NAME="test">value</PREF>
    </ACTION>

  </RULE>
  <RULE ID="2">
    <!--<FILTER NAME="IPVer">0x40</FILTER>
    <FILTER NAME="Proto">udp</FILTER>-->
    <FILTER NAME="SrcIP">*</FILTER>

    <ACTION NAME="pktid_crc32">
    </ACTION>
   
    <ACTION NAME="pktid_md5">
    </ACTION>
  </RULE>
</RULESET>

=== DanielArndt/netmate-flowcalc/netAI-rules-stats-ni.xml
<?xml version ="1.0" encoding="UTF-8"?>
<!DOCTYPE RULESET SYSTEM "rulefile.dtd"> 
<RULESET ID="1">
  <!-- global part is the default for all rules -->
  <!-- overwritten by rule specific configuration -->
  <GLOBAL>
 
    <ACTION NAME="netai_flowstats">
      <PREF NAME="Idle_Threshold">1000000</PREF>
    </ACTION>

    <EXPORT NAME="ac_file">
      <PREF NAME="Filename">/home/darndt/netmate.out</PREF>
      <PREF NAME="FlowID">no</PREF>
      <PREF NAME="ExportStatus">no</PREF>
    </EXPORT>

    <!-- export interval in seconds -->
    <!-- PREF NAME="Interval">10</PREF>  -->
   
  </GLOBAL>

  <RULE ID="1">
    <!-- match all udp/tcp packets -->
    <FILTER NAME="SrcIP">*</FILTER>
    <FILTER NAME="SrcPort">*</FILTER>
    <FILTER NAME="DstIP">*</FILTER>
    <FILTER NAME="DstPort">*</FILTER>
    <FILTER NAME="Proto">tcp,udp</FILTER>

    <PREF NAME="auto">yes</PREF>
    <PREF NAME="bidir">yes</PREF>
    <PREF NAME="FlowTimeout">600</PREF>
  </RULE>

</RULESET>

=== DanielArndt/netmate-flowcalc/etc/example_rules2.xml
<?xml version ="1.0" encoding="UTF-8"?>
<!DOCTYPE RULESET SYSTEM "rulefile.dtd"> 
<RULESET ID="1">
  <GLOBAL>
    <!-- defaults for all rules can be overwritten by rule
         specific configuration -->

    <!-- how long the rules are active (in seconds) -->
    <PREF NAME="Duration">1000</PREF>
    <!-- export interval -->
    <PREF NAME="Interval">10</PREF>

    <ACTION NAME="show_ascii"></ACTION>

    <EXPORT NAME="text_file">
      <!-- by default each rule is exported into a separate file
           named like the rule ID; the following line can be uncommented
           to export all rules into a single file-->
      <!--<PREF NAME="Filename">exportfile</PREF>-->

      <!-- the following can be uncommented to create one file per action
           per rule -->
      <!--<PREF NAME="Multifile">yes</PREF>-->

      <!-- specify user -->
      <!--<PREF NAME="ExportUser">nobody</PREF>-->
    </EXPORT>
  </GLOBAL>
  <RULE ID="1">
    <!-- single masked value -->
    <FILTER NAME="SrcIP" MASK="255.255.255.0">193.175.133.0</FILTER>
    <!-- list of values -->
    <!-- FILTER NAME="Proto">udp,tcp</FILTER -->

    <ACTION NAME="bandwidth">
      <PREF NAME="Interval">5</PREF>
    </ACTION>

    <ACTION NAME="pktlen">
    </ACTION>

  </RULE>
  <RULE ID="2">
    <FILTER NAME="SrcIP">*</FILTER>
    <FILTER NAME="Proto">udp,tcp</FILTER>
    <!-- range -->
    <FILTER NAME="DstPort">1-1024</FILTER>    

    <ACTION NAME="jitter">
    </ACTION>

    <ACTION NAME="port_use">
    </ACTION>
  </RULE>

  <RULE ID="3">
    <FILTER NAME="SrcIP">*</FILTER>
    <FILTER NAME="DstIP">www.google.com</FILTER>
    <FILTER NAME="DstPort">http</FILTER>

    <ACTION NAME="bandwidth">
    </ACTION>
 
    <!-- match both directions of the flow -->
    <PREF NAME="bidir">yes</PREF>

    <!-- start 10 seconds later -->
    <PREF NAME="Start">+10</PREF>

    <!-- overwrite default settings -->
    <PREF NAME="Duration">990</PREF>
    <PREF NAME="Interval">5</PREF>
  </RULE>
</RULESET>
